[general]
webp_quality = 50
scratch_path = "./tmp"
cache_path = "./cache"
bhl_api_key = ''
id_list = "item-ids.txt"
# webp doesn't allow for more than 16,000 pixels
# 8000 is reasonable and won't cause out of memory errors.
# Note: This will still use up to 4 GB of resident RAM when resizing.
max_image_dimension = "8000"

[logging]
path = "./logs"
filename = "update-aws-item.log"

[webp_sizes]
# WebP Sizes. Don't change without a very good reason
# Ordered largest to smallest. Labels are are used as suffixes.
large = 930
medium = 465
small = 235
thumb = 150

[rabbitmq]
host = ""
port = 5672
vhost = "/"
username = "guest"
password = "guest"
concurrency = 1

[queues]
new-items = ""
updated-items = ""
ocr-only = ""
error_queue_suffix = ".error"  # optional: failed items are re-published here
