[general]
webp_quality = 50
scratch_path = "./tmp"
cache_path = "./cache"
bhl_api_key = ''
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
id_list = "item-ids.txt"


[webp_sizes]
# WebP Sizes. Don't change without a very good reason
# Ordered largest to smallest. Labels are are used as suffixes.
large = 930
medium = 465
small = 235
thumb = 150

