[general]
webp_quality = 50
scratch_path = "./tmp"
cache_path = "./cache"
bhl_api_key = ''
id_list = "item-ids.txt"

[logging]
path = "./logs"
filename = "update-aws-item.log"

[webp_sizes]
# WebP Sizes. Don't change without a very good reason
# Ordered largest to smallest. Labels are are used as suffixes.
large = 930
medium = 465
small = 235
thumb = 150

